### ISSUE TITLE
Scaling down Hazelcast cluster causes Python client to lose connection

### ISSUE THREAD

**Issue by googlielmo** [hazelcast/hazelcast-python-client#182]
## Description

Scaling down Hazelcast cluster causes Python client to lose connection even with `redo_operation` set to `True`.

## Steps to reproduce

Create Hazelcast cluster with 2 members.

Run client program that connects and issues periodical requests, such as:
```
import hazelcast
import logging
import random

if __name__ == "__main__":
    logging.basicConfig()
    logging.getLogger().setLevel(logging.INFO)

    config = hazelcast.ClientConfig()
    config.network_config.redo_operation = True

    client = hazelcast.HazelcastClient(config)

    my_map = client.get_map("map").blocking()
    my_map.put("key", "value")

    if my_map.get("key") == "value":
        print("Connection Successful!")
        print("Now, `map` will be filled with random entries.");
        while True:
            random_key = random.randint(1, 100000)
            my_map.put("key" + str(random_key), "value" + str(random_key))
            my_map.get("key" + str(random.randint(1,100000)))
            if random_key % 10 == 0:
                print("Map size:" + str(my_map.size()))
    else:
        raise Exception("Connection failed, check your configuration.")


    client.shutdown()
```

Now scale the cluster up to 4 members. Connection will not be lost. Scale down to 2 members
again, an error will occur and the program will exit.

```
WARNING: [3.12.1] [guglielmo-net-04] [hz.client_0] Connection closed by server
WARNING:HazelcastClient.Connection[0](33.11.106.108:30023):[guglielmo-net-04] [hz.client_0] Connection closed by server
Nov 13, 2019 10:40:18 AM HazelcastClient.LifecycleService
INFO: [3.12.1] [guglielmo-net-04] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is DISCONNECTED
INFO:HazelcastClient.LifecycleService:[guglielmo-net-04] [hz.client_0] (20190319 - 3b38a46) HazelcastClient is DISCONNECTED
Nov 13, 2019 10:40:18 AM HazelcastClient.Connection[1](33.11.118.111:30023)
WARNING: [3.12.1] [guglielmo-net-04] [hz.client_0] Connection closed by server
WARNING:HazelcastClient.Connection[1](33.11.118.111:30023):[guglielmo-net-04] [hz.client_0] Connection closed by server
Nov 13, 2019 10:40:18 AM HazelcastClient.ClusterService
WARNING: [3.12.1] [guglielmo-net-04] [hz.client_0] Connection closed to owner node. Trying to reconnect.
WARNING:HazelcastClient.ClusterService:[guglielmo-net-04] [hz.client_0] Connection closed to owner node. Trying to reconnect.
Nov 13, 2019 10:40:19 AM HazelcastClient.ClusterService
INFO: [3.12.1] [guglielmo-net-04] [hz.client_0] Connecting to Address(host=100.96.6.2, port=30023)
INFO:HazelcastClient.ClusterService:[guglielmo-net-04] [hz.client_0] Connecting to Address(host=100.96.6.2, port=30023)
Nov 13, 2019 10:41:39 AM HazelcastClient.Connection[2](33.11.101.6:30023)
WARNING: [3.12.1] [guglielmo-net-04] [hz.client_0] Connection closed by server
WARNING:HazelcastClient.Connection[2](33.11.101.6:30023):[guglielmo-net-04] [hz.client_0] Connection closed by server
Nov 13, 2019 10:41:39 AM HazelcastClient.Connection[3](33.11.120.0:30023)
WARNING: [3.12.1] [guglielmo-net-04] [hz.client_0] Connection closed by server
WARNING:HazelcastClient.Connection[3](33.11.120.0:30023):[guglielmo-net-04] [hz.client_0] Connection closed by server
Traceback (most recent call last):
  File "client.py", line 38, in <module>
    my_map.put("key" + str(random_key), "value" + str(random_key))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hazelcast/future.py", line 274, in f
    return result.result()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hazelcast/future.py", line 61, in result
    six.reraise(self._exception.__class__, self._exception, self._traceback)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hazelcast/future.py", line 145, in callback
    future.set_result(continuation_func(f, *args))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hazelcast/proxy/base.py", line 12, in default_response_handler
    response = future.result()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hazelcast/future.py", line 61, in result
    six.reraise(self._exception.__class__, self._exception, self._traceback)
  File "<string>", line 3, in reraise
hazelcast.exception.TimeoutError: Request timed out after 120 seconds.
Exception in thread hazelcast-reactor (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/home/ubuntu/.local/lib/python2.7/site-packages/hazelcast/reactor.py", line 47, in _loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by mdumandag** [comment]
Setting milestone to 3.12.4 since we verified that client now works on scaling up/down

**Comment by mdumandag** [comment]
Closing this as we have verified that the client can work with scale-ups/downs.

This issue was left open to fix 3.x versions of the client but we are not doing any developments there anymore. Hence, I am closing this.
