### ISSUE TITLE
test_add_distributed_object_listener_object_destroyed

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast-python-client#238]
The `test_add_distributed_object_listener_object_destroyed` failed on the PR builder.

It seems that the `DESTROYED` event is not received.

```
16:12:18 ======================================================================
16:12:18 ERROR: test_add_distributed_object_listener_object_destroyed (tests.proxy.distributed_objects_test.DistributedObjectsTest)
16:12:18 ----------------------------------------------------------------------
16:12:18 Traceback (most recent call last):
16:12:18   File "/home/jenkins/jenkins_slave/workspace/python3.7-pr-builder/tests/proxy/distributed_objects_test.py", line 77, in test_add_distributed_object_listener_object_destroyed
16:12:18     self.assertTrueEventually(assert_event)
16:12:18   File "/home/jenkins/jenkins_slave/workspace/python3.7-pr-builder/tests/base.py", line 64, in assertTrueEventually
16:12:18     raise
16:12:18 RuntimeError: No active exception to reraise
```

http://jenkins.hazelcast.com/job/python3.7-pr-builder/183/

**Comment by mdumandag** [comment]
This test failed again on one of the nightly test runners. I couldn't find the problem behind it yet. Added more logs in #282 to understand the situation better for the next time
